### plugin configuration (lazy load)
###  -- to ".dein.toml" and ".dein_lazy.toml", configurations are splited.

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
	let g:quickrun_config = {
	\	"_" : {
	\		"outputter/buffer/split" : ":botright",
	\		"outputter/error/success" : "buffer",
	\		"outputter/error/error/" : "quickfix",
	\		"outputter/buffer/into" : "1",
	\		"outputter/quickfix/errorformat" : "%f:%l,%m in %f on line %l",
	\		"outputter/buffer/close_on_empty" : 1,
	\		"outputter" : "error"
	\  }
	\}
	let g:quickrun_no_default_key_mappings = 1
	nnoremap \r :write<CR>:QuickRun -mode n<CR>
	xnoremap \r :<C-U>write<CR>gv:QuickRun -mode v<CR>
	nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
	au FileType qf nnoremap <silent><buffer>q :quit<CR>
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_ft = [ 'python', 'c', 'sh', 'ruby' ]
