### .dein.toml
#
# if in trouble,
# 1). brew update,brew upgrade neovim
# 2). pip install --upgrade neovim
# 3). (on vim) :UpdateRemotePlugins,:checkhealth,:call dein#update()
#

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_source = '''
  let g:fzf_tags_command = 'ctags -R -f .tags'
  command! -bang -nargs=* Files call
    \ fzf#vim#files(<q-args>,
    \            <bang>0 ? fzf#vim#with_preview('up:60%')
    \                    : fzf#vim#with_preview('right:50%:hidden', '?'),
    \            <bang>0)
'''

[[plugins]]
repo = 'simnalamburt/vim-mundo'
hook_source = '''
  let g:mundo_preview_bottom = 1
  let g:mundo_width = 35
  let g:mundo_preview_statusline = '[Undotree-preview]'
  let g:mundo_tree_statusline  = '[Undotree]'
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_source = '''
  let g:indentLine_enabled = 1
  let g:indentLine_fileType = ['c','sh','php','smarty','python','ruby']
  let g:indentLine_char = '¦'
  let g:indentLine_first_char = '¦'
  let g:indentLine_showFirstIndentLevel = 1
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_source = '''
  let g:tagbar_autofocus = 1
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  nmap <silent> <C-p> <Plug>(ale_previous_wrap)
  nmap <silent> <C-n> <Plug>(ale_next_wrap)
  let g:ale_lint_on_text_changed = 'normal'
  let g:ale_lint_on_insert_leave = 1
  function! LinterStatus() abort
    let l:counts = ale#statusline#Count(bufnr(''))

    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors

    return l:counts.total == 0 ? '0' : printf(
    \   '%dW %dE',
    \   all_non_errors,
    \   all_errors
    \)
  endfunction
'''
