### .dein.toml
#
# in case you need to update,
# 1). brew update,brew upgrade neovim
# 2). pip install --upgrade pynvim
# 3). (on vim) :UpdateRemotePlugins,:checkhealth,:call dein#update()

### manage
[[plugins]]
repo = 'Shougo/dein.vim'

### search
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

### edit
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
  let g:LanguageClient_serverCommands = {
  \ 'c': ['clangd'],
  \ 'javascript': ['javascript-typescript-stdio'],
  \ 'typescript': ['javascript-typescript-stdio'],
  \ 'python': ['pyls'],
  \}
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
  let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
'''

### debug
[[plugins]]
repo = 'vim-vdebug/vdebug'

### external integration
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_sign_modified_removed = '~'
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  let g:tagbar_autofocus = 1
'''

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = '''
  let g:ref_use_vimproc = 1
  let g:ref_phpmanual_path = '/Users/naoki/usr/doc/ref/php-chunked-xhtml'
'''

### filetype sources
[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'blueyed/smarty.vim'
on_ft = 'smarty'

### utility
[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
hook_source = '''
  let g:mundo_preview_bottom = 1
  let g:mundo_width = 35
  let g:mundo_preview_statusline = '[Undotree-preview]'
  let g:mundo_tree_statusline  = '[Undotree]'
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'tpope/vim-speeddating'

[[plugins]]
repo = 'osyo-manga/vim-trip'

[[plugins]]
repo = 'haya14busa/vim-edgemotion'

[[plugins]]
repo = 'andymass/vim-tradewinds'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'qpkorr/vim-bufkill'

[[plugins]]
repo = 'dahu/vim-fanfingtastic'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
