### .dein_lazy.toml

### debug
[[plugins]]
repo = 'vim-vdebug/vdebug'
on_ft = ['javascript','perl','php','python','ruby']
hook_add = '''
  nnoremap [vdb] <Nop>
  nmap <Space>d [vdb]
  nnoremap <silent> [vdb]l :BreakpointWindow<CR>
  nnoremap <silent> [vdb]q :BreakpointRemove *<CR>
  let g:vdebug_keymap = {
  \  'run' : '<C-n>',
  \  'run_to_cursor' : '<C-m>',
  \  'step_over' : '[vdb]n',
  \  'step_into' : '[vdb]i',
  \  'step_out' : '[vdb]N',
  \  'set_breakpoint' : '<Space>m',
  \  'eval_under_cursor' : '[vdb]e',
  \  'detach' : '[vdb]c',
  \  'close' : '[vdb]C',
  \}
  let g:vdebug_options = {
  \    'port' : 9000,
  \    'timeout' : 20,
  \    'server' : '',
  \    'on_close' : 'detach',
  \    'break_on_open' : 0,
  \    'ide_key' : '',
  \    'debug_window_level' : 0,
  \    'debug_file_level' : 0,
  \    'debug_file' : '',
  \    'path_maps' : {"":""},
  \    'watch_window_style' : 'expanded',
  \    'marker_default' : '⬦',
  \    'marker_closed_tree' : '▸',
  \    'marker_open_tree' : '▾',
  \    'sign_breakpoint' : '>',
  \    'sign_current' : '>>',
  \    'sign_disabled' : '<<',
  \    'continuous_mode'  : 1
  \}
'''
# for remote debugging -> {path_maps(remote:local)}

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  nnoremap [debug] <Nop>
  nmap <Space>d [debug]
  nnoremap <silent> [debug]d :GoDebugStart<CR>
  nnoremap <silent> [debug]D :GoDebugTest<CR>
  nnoremap <silent> <Space>m :GoDebugBreakpoint<CR>
  nnoremap <silent> <C-n> :GoDebugContinue<CR>
  nnoremap <silent> [debug]n :GoDebugNext<CR>
  nnoremap <silent> [debug]N :GoDebugStepOut<CR>
  nnoremap <silent> [debug]i :GoDebugStep<CR>
  nnoremap <silent> [debug]C :GoDebugStop<CR>
  let g:go_debug_windows = {
        \ 'stack': 'botright 15new',
        \ 'out':   'belowright 5new',
        \ 'vars':  'topleft 40vnew',
  \ }
  let g:go_code_completion_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
  let g:go_def_mapping_enabled = 0
  let g:go_fmt_command = "goimports"
'''

### filetype source
[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = 'csv'

[[plugins]]
repo = 'blueyed/smarty.vim'
on_ft = 'smarty'
