### .dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
	call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
	call denite#custom#var('grep', 'command', ['ag'])
	call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#hook_source = '''
#	let g:deoplete#enable_at_startup = 1
#	let g:deoplete#auto_complete_delay = 0
#'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
