### initialization

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
'''

### lazy load

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
	let g:jedi#rename_command = "<leader>R"
	autocmd FileType python setlocal completeopt-=preview
'''
	|-need modification with its speed, halted.

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [ 'html']
hook_add = '''
	inoremap [emmet] <Nop>
	imap <C-Space> [emmet]
	autocmd FileType html imap <buffer><expr><C-Space>
	\	emmet#isExpandable() ? "\<plug>(emmet-expand-abbr)" :
	\	"\<tab>"
	let g:user_emmet_settings = {
	\	'variables' : {
	\	'lang' : 'ja'
	\	}
	\}
'''
