[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#on_event = 'InsertCharPre'
#hook_source = '''
#  let g:deoplete#enable_at_startup = 1
#  let g:deoplete#auto_complete_delay = 0
#'''

[[plugins]]
repo = 'Shougo/denite.nvim'
