[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'cohama/lexima.vim'
on_ft = [ 'python', 'ruby', 'c', 'sh' ]

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [ 'html', 'php']
