### conf on lazy load

## too slow for this device to use.
#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'
#hook_add = '''
#	autocmd FileType python setl smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
#	autocmd FileType python setlocal completeopt-=preview
#	let g:jedi#rename_command = "<leader>v"
#    let g:jedi#completions_command = "<C-n>"
#	let g:jedi#popup_on_dot=0
#	let g:jedi#smart_auto_mappings = 0
#'''

#[[plugins]]
#repo = 'thinca/vim-quickrun'
#hook_add = '''
#	let g:quickrun_config = {
#	\	"_" : {
#	\		"outputter/buffer/split" : ":botright",
#	\		"outputter/error/success" : "buffer",
#	\		"outputter/error/error/" : "quickfix",
#	\		"outputter/buffer/into" : "1",
#	\		"outputter/quickfix/errorformat" : "%f:%l,%m in %f on line %l",
#	\		"outputter/buffer/close_on_empty" : 1,
#	\		"outputter" : "error"
#	\  }
#	\}
#	let g:quickrun_no_default_key_mappings = 1
#	nnoremap \r :QuickRun -mode n<CR>
#	xnoremap \r :QuickRun -mode v<CR>
#	nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
#	au FileType qf nnoremap <silent><buffer>q :quit<CR>
#'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_ft = [ 'python', 'ruby', 'c', 'sh']

#[[plugins]]
#repo = 'mattn/emmet-vim'
#on_ft = [ 'html']
#hook_add = '''
#	inoremap [emmet] <Nop>
#	imap <C-Space> [emmet]
#	autocmd FileType html imap <buffer><expr><C-Space>
#	\	emmet#isExpandable() ? "\<plug>(emmet-expand-abbr)" :
#	\	"\<tab>"
#	let g:user_emmet_settings = {
#	\	'variables' : {
#	\	'lang' : 'ja'
#	\	}
#	\}
#'''
